create table if not exists private.gestion_integrantes_eliminaciones (
  id bigint generated by default as identity primary key,
  integrante_id bigint not null,
  admin_user_id uuid,
  eliminado_at timestamptz not null default now(),
  motivo text,
  pais_iso2 text,
  tenia_moodle boolean not null default false,
  resumen jsonb not null default '{}'::jsonb
);

revoke all on table private.gestion_integrantes_eliminaciones from public, anon, authenticated;

create or replace function public.admin_gestion_integrante_eliminar(
  p_id bigint,
  p_documento_confirmacion text,
  p_motivo text default null
) returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare
  v_actual public.integrantes%rowtype;
  v_documento_actual text;
  v_documento_confirmado text;
  v_resumen jsonb;
begin
  if not private.es_admin_gestion() then
    raise exception 'No autorizado';
  end if;

  select * into v_actual
  from public.integrantes
  where id = p_id
  for update;

  if not found then
    raise exception 'El integrante ya no existe. Actualiza la lista.';
  end if;

  v_documento_actual := regexp_replace(coalesce(v_actual.documento, ''), '\D', '', 'g');
  v_documento_confirmado := regexp_replace(coalesce(p_documento_confirmacion, ''), '\D', '', 'g');

  if v_documento_confirmado = '' or v_documento_confirmado is distinct from v_documento_actual then
    raise exception 'El documento de confirmación no coincide con el integrante.';
  end if;

  select jsonb_build_object(
    'puntos_eventos', (select count(*) from public.puntos_eventos where integrante_id = p_id),
    'participa_respuestas', (select count(*) from public.participa_respuestas where integrante_id = p_id),
    'calificaciones_moodle', (select count(*) from public.calificaciones_moodle where integrante_id = p_id),
    'correos_registro', (select count(*) from public.cola_correos_registro where integrante_id = p_id),
    'auth_links', (select count(*) from public.integrante_auth_links where integrante_id = p_id)
  ) into v_resumen;

  -- Históricos que conviene conservar, quitando solamente la referencia personal.
  update public.moodle_admin_auditoria set integrante_id = null where integrante_id = p_id;
  update public.participa_campanas set created_by = null where created_by = p_id;
  update public.participa_consultas set created_by = null where created_by = p_id;

  -- Relaciones de rol/actividad que bloquean el borrado y dejan de tener sentido sin el integrante.
  delete from public.estudio_moderadores where integrante_id = p_id;
  delete from public.mapa_confirmaciones where integrante_id = p_id;
  delete from public.mapa_moderadores where integrante_id = p_id;
  delete from public.mapa_reportes where integrante_id = p_id;

  insert into private.gestion_integrantes_eliminaciones (
    integrante_id,
    admin_user_id,
    motivo,
    pais_iso2,
    tenia_moodle,
    resumen
  ) values (
    p_id,
    (select auth.uid()),
    nullif(trim(coalesce(p_motivo, '')), ''),
    v_actual.pais_iso2,
    v_actual.moodle_user_id is not null,
    v_resumen
  );

  delete from public.integrantes where id = p_id;

  return jsonb_build_object(
    'id', v_actual.id,
    'nombre', trim(concat_ws(' ', v_actual.nombres, v_actual.apellidos)),
    'documento', v_actual.documento,
    'moodle_conservado', v_actual.moodle_user_id is not null,
    'resumen', v_resumen
  );
end;
$$;

revoke all on function public.admin_gestion_integrante_eliminar(bigint, text, text) from public, anon;
grant execute on function public.admin_gestion_integrante_eliminar(bigint, text, text) to authenticated;
grant execute on function public.admin_gestion_integrante_eliminar(bigint, text, text) to service_role;
